version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      POSTGRES_DB: mockbuster
    working_dir: /app
    ports:
      - 5432:5432
    volumes:
      - .:/app
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  redis:
    image: redis:7
    restart: unless-stopped
    user: "$UID:$GID"
    ports:
      - 6379:6379
    working_dir: /app
    volumes:
      - .:/app

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
  #   restart: unless-stopped
  #   volumes:
  #     - ./elasticsearch/certs:/usr/share/elasticsearch/config/certs
  #   ports:
  #     - 9200:9200
  #   env_file: 
  #     - .env

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.7.1
  #   restart: unless-stopped
  #   ports:
  #     - 5601:5601
  #   env_file: 
  #     - .env
