[package]
name = "top_ten_view"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "./src/lib.rs"

[dependencies]
components = { path = "./../components" }
wasm-bindgen = { workspace = true }
yew = { workspace = true }

