[package]
name = "home_view"
version = "0.0.1"
edition = "2021"
include = ["./../../locales"]

[lib]
crate-type = ["cdylib", "rlib"]
path = "./src/lib.rs"

[dependencies]
components = { path = "./../components" }
wasm-bindgen = { workspace = true }
yew = { workspace = true }