[package]
name = "validators"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "./validators.rs"

[dependencies]
lazy_static = "1.4.0"
regex = "1.9.6"
serde = { workspace = true }
serde_json = "1.0"
validator = { workspace = true }