[package]
name = "models"
version = "0.0.1"
edition = "2021"

[lib]
path = "./lib.rs"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
sea-orm = { workspace = true, optional = true }
yew = { workspace = true }

[features]
db_models = ["sea-orm"]
stubs = []
